export enum ProcessingStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  RECORDED_IN_SYSTEM = "RECORDED_IN_SYSTEM",
  CONFIRMATION_PRESENT = "CONFIRMATION_PRESENT",
  CONFIRMATION_MISSING = "CONFIRMATION_MISSING"
}
